### PR TITLE
fix(MedalShowcase): dark mode compatibility 

### LINKED ISSUE #79: bug: MedalShowcase 组件部分元素颜色锁死导致黑暗模式出现问题

### PR DESCRIPTION
**Pull request by StarHeartHunt**
fix #79

### CODE REVIEW

**Comment by StarHeartHunt** [comment]
@Yanstory 看看配色要不要改

File: src/widgets/MedalList/MedalGroup.vue [hunk 1]
```diff
@@ -112,14 +112,15 @@ export default defineComponent({
...
+                class="color-white!"
                 :color="showTrimed ? '#637cad' : '#000'"
                 @click="showTrimed = !showTrimed"
               >
                 <div>
                   <span
                     :class="[
                       'mdi',
-                      'mdi-chevron-up-circle' + (showTrimed ? '' : '-outline'),
+                      `mdi-chevron-up-circle${!showTrimed && '-outline'}`,
```
Comment (StarHeartHunt) [inline src/widgets/MedalList/MedalGroup.vue:123]:
```suggestion
                      `mdi-chevron-up-circle${showTrimed ? '-outline' : ''}`,
```

File: src/widgets/MedalList/MedalGroup.vue [hunk 2]
```diff
@@ -112,14 +112,15 @@ export default defineComponent({
...
+                class="color-white!"
                 :color="showTrimed ? '#637cad' : '#000'"
                 @click="showTrimed = !showTrimed"
               >
                 <div>
                   <span
                     :class="[
                       'mdi',
-                      'mdi-chevron-up-circle' + (showTrimed ? '' : '-outline'),
+                      `mdi-chevron-up-circle${showTrimed ? '-outline' : ''}`,
```
Comment (StarHeartHunt) [inline src/widgets/MedalList/MedalGroup.vue:123]:
```suggestion
                      `mdi-chevron-up-circle${showTrimed ? '' : '-outline'}`,
```

**Review by daflyinbed — APPROVED** [review]
